package server;

import javax.swing.*;
import java.awt.*;
import java.util.Set;

/**
 * The GUI class for the server
 */
public class ServerGUI {

    private JLabel userLabel;
    private JTextArea userList;
    private JLabel logLabel;
    private JTextArea logArea;
    private JPanel mainFrame;

    private static ChatServer serverThread;
    private static JFrame frame;

    /**
     * Constructor, it starts the server
     */
    private ServerGUI() {
        serverThread = new ChatServer(this);
        new Thread(serverThread).start();
    }

    /**
     * GUI main
     * @param args args
     */
    public static void main(String[] args) {
        frame = new JFrame("ServerGUI");
        frame.setContentPane(new ServerGUI().mainFrame);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        frame.setResizable(false);
        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                serverThread.forceClose();
            }
        });
    }

    /**
     *  Update the list of connected users
     * @param usernames a set containing the usernames of the connected users
     */
    void updateUsers(Set<String> usernames) {
        userList.setText("");
        for (String user : usernames) {
            userList.append(user + "\n");
        }
    }

    /**
     * Closes the frame
     */
    void forceClose() {
        frame.dispose();
    }

    /**
     * Adds a new event (incoming connection, login, logout) to the log area
     * @param event the description of the event
     */
    void addEvent(String event) {
        logArea.append(event + "\n");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainFrame = new JPanel();
        mainFrame.setLayout(new GridBagLayout());
        mainFrame.setBackground(new Color(-2563870));
        mainFrame.setMinimumSize(new Dimension(500, 200));
        mainFrame.setPreferredSize(new Dimension(500, 200));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setBackground(new Color(-2563870));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridheight = 3;
        gbc.fill = GridBagConstraints.BOTH;
        mainFrame.add(panel1, gbc);
        userLabel = new JLabel();
        userLabel.setForeground(new Color(-12961222));
        userLabel.setText("Online Users");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        mainFrame.add(userLabel, gbc);
        logArea = new JTextArea();
        logArea.setBackground(new Color(-2563870));
        logArea.setEditable(false);
        logArea.setForeground(new Color(-12961222));
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainFrame.add(logArea, gbc);
        logLabel = new JLabel();
        logLabel.setForeground(new Color(-12961222));
        logLabel.setText("Event Log");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        mainFrame.add(logLabel, gbc);
        userList = new JTextArea();
        userList.setBackground(new Color(-2563870));
        userList.setEditable(false);
        userList.setForeground(new Color(-12961222));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainFrame.add(userList, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainFrame;
    }

}
